Repository nucleos/NucleosUserBundle, pull requests merged in 2020-11, with the labels that each got.

#131 Add phpmd
  .github/workflows/continuous-integration.yml
  composer.json
  phpmd.xml
  src/Action/ChangePasswordAction.php
  src/Action/LoginAction.php
  src/Action/SendEmailAction.php
  src/Command/CreateUserCommand.php
  src/Command/RoleCommand.php
  src/DependencyInjection/NucleosUserExtension.php
  src/Model/User.php
  src/Security/UserChecker.php
  tests/DependencyInjection/NucleosUserExtensionTest.php
  tests/Util/UserManipulatorTest.php
  vendor-bin/tools/composer.json
  vendor-bin/tools/composer.lock
Labels: automerge, pedantic

#136 Drop doctrine/mongodb-odm 1
  composer.json
Labels: dependency

#140 Add workflow filter to CI link in README
  README.md
Labels: automerge, pedantic

#141 Add more specific phpdoc
  phpstan-baseline.neon
  src/Doctrine/GroupManager.php
  src/Doctrine/UserManager.php
  src/Model/GroupManagerInterface.php
  src/Model/UserManagerInterface.php
  tests/Doctrine/UserManagerTest.php
Labels: bugfix
