Repository nucleos/NucleosUserBundle, pull requests merged in 2021-09, with the labels that each got.

#421 Adapt phpstan config for the new getArgument() return type
  phpstan-baseline.neon
Labels: Enhancement

#423 Update composer.json for version 2.x (Symfony 5.3+)
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  composer.json
  src/Model/UserInterface.php
Labels: dependency

#420 Replace the legacy password encoder security component
  src/Model/UserInterface.php
  src/Resources/config/util.php
  src/Util/PasswordUpdater.php
  tests/Fixtures/SaltedPasswordHasher.php
  tests/Util/PasswordUpdaterTest.php
Labels: BC Break, Enhancement

#426 Use AuthenticationUtils to access login data
  phpstan-baseline.neon
  src/Action/LoginAction.php
  src/Resources/config/security.php
Labels: Enhancement

#427 Drop support for PHP 7.3
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  composer.json
Labels: dependency

#437 Add type hints to test classes
  tests/Action/LoginActionIntegrationTest.php
  tests/Action/RequestResetActionIntegrationTest.php
  tests/App/AppKernel.php
  tests/App/Entity/TestUser.php
  tests/DependencyInjection/NucleosUserExtensionTest.php
  tests/Doctrine/UserManagerTest.php
  tests/EventListener/FlashListenerTest.php
  tests/Security/EmailProviderTest.php
  tests/Security/EmailUserProviderTest.php
  tests/Security/UserProviderTest.php
  tests/Util/CanonicalFieldsUpdaterTest.php
  tests/Util/PasswordUpdaterTest.php
  tests/Util/UserManipulatorTest.php
Labels: Enhancement

#442 Fix stan errors
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Validator/Constraints/PatternValidator.php
Labels: Enhancement

#443 Move form buttons to actions
  src/Action/ChangePasswordAction.php
  src/Action/RequestResetAction.php
  src/Action/ResetAction.php
  src/Form/Type/ChangePasswordFormType.php
  src/Form/Type/RequestPasswordFormType.php
  src/Form/Type/ResettingFormType.php
Labels: Enhancement

#445 Remove egulias/email-validator dependency
  composer.json
Labels: dependency

#446 Remove `nucleos_user.session` alias
  src/DependencyInjection/NucleosUserExtension.php
Labels: Enhancement

#444 Add property type hints
  src/Action/AccountDeletionAction.php
  src/Action/ChangePasswordAction.php
  src/Action/CheckEmailAction.php
  src/Action/LoggedinAction.php
  src/Action/LoginAction.php
  src/Action/RequestResetAction.php
  src/Action/ResetAction.php
  src/Action/SendEmailAction.php
  src/Command/ActivateUserCommand.php
  src/Command/ChangePasswordCommand.php
  src/Command/CreateUserCommand.php
  src/Command/DeactivateUserCommand.php
  src/Command/RoleCommand.php
  src/DependencyInjection/NucleosUserExtension.php
  src/Doctrine/GroupManager.php
  src/Doctrine/UserListener.php
  src/Doctrine/UserManager.php
  src/Event/AccountDeletionEvent.php
  src/Event/AccountDeletionResponseEvent.php
  src/Event/FilterGroupResponseEvent.php
  src/Event/FilterUserResponseEvent.php
  src/Event/FormEvent.php
  src/Event/GetResponseAccountDeletionEvent.php
  src/Event/GetResponseLoginEvent.php
  src/Event/GetResponseUserEvent.php
  src/Event/GroupEvent.php
  src/Event/UserEvent.php
  src/EventListener/AuthenticationListener.php
  src/EventListener/FlashListener.php
  src/EventListener/LastLoginListener.php
  src/EventListener/LocaleEventListener.php
  src/EventListener/ResettingListener.php
  src/Form/Model/AccountDeletion.php
  src/Form/Model/ChangePassword.php
  src/Form/Model/Resetting.php
  src/Form/Type/AccountDeletionFormType.php
  src/Form/Type/ChangePasswordFormType.php
  src/Form/Type/LoginFormType.php
  src/Form/Type/ResettingFormType.php
  src/Mailer/Mail/ResettingMail.php
  src/Mailer/Mailer.php
  src/Model/Group.php
  src/Model/User.php
  src/Model/UserManager.php
  src/Security/LoginManager.php
  src/Security/UserProvider.php
  src/Util/CanonicalFieldsUpdater.php
  src/Util/PasswordUpdater.php
  src/Util/UserManipulator.php
  src/Validator/Constraints/Pattern.php
  src/Validator/Initializer.php
Labels: Enhancement
