Repository nucleos/NucleosUserBundle, pull requests merged in 2021-01, with the labels that each got.

#191 Force php version when running psalm
  .github/workflows/continuous-integration.yml
  vendor-bin/tools/composer.json
  vendor-bin/tools/composer.lock
Labels: pedantic

#207 Move buttons to action
  src/Action/LoginAction.php
  src/Form/Type/LoginFormType.php
  tests/Action/LoginActionIntegrationTest.php
Labels: feature

#227 Fixing typo in routing
  src/Resources/config/routing/security.xml
Labels: bugfix
